# Generated by Django 3.0.5 on 2024-10-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
